"""Add Battle modezl

Revision ID: bb408aac9318
Revises: 5bf57887c12a
Create Date: 2024-11-08 13:43:04.172267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb408aac9318'
down_revision = '5bf57887c12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creator_results', sa.String(), server_default='[null,null,null]', nullable=True))
        batch_op.add_column(sa.Column('opponent_results', sa.String(), server_default='[null,null,null]', nullable=True))
        batch_op.create_foreign_key(
            'fk_battle_winner_id_user',  # Название внешнего ключа
            'user',                      # Таблица, на которую ссылаемся
            ['winner_id'],               # Колонка в текущей таблице
            ['id'],                      # Колонка в таблице user
            ondelete='SET NULL'          # Что делать при удалении записи
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_battle_winner_id_user', type_='foreignkey')
        batch_op.drop_column('opponent_results')
        batch_op.drop_column('creator_results')
        batch_op.drop_column('winner_id')

    # ### end Alembic commands ###
